### PR TITLE
Update EM driver to report kWh and possibility to use the offset 

### PR DESCRIPTION
**Pull request by catalinvr**
Hi team,

I added the possibility to set the power offset for each channel based on the reading from the provider energy meter.
Also, I switched the `energy` value from Wh to kWh. This is common in Europe.

Hope that this will help the community. For me is really useful because I can copy paste the values from here when I need to enter the reading to the electricity provider.

Thank you

### CODE REVIEW

**Comment by maxtacu** [comment]
Hey @catalinvr thanks for your contribution! I think it would be better to create a separate `if` for `SHEM-3` only and place the `input..` for channel 2 offset there (since ch2 is available only in Shelly 3EM)

**Comment by sgrayban** [comment]
> Hey @catalinvr thanks for your contribution! I think it would be better to create a separate `if` for `SHEM-3` only and place the `input..` for channel 2 offset there (since ch2 is available only in Shelly 3EM)

I agree. Won't merge until this is done.

**Comment by sgrayban** [comment]
Wont merge

**Comment by catalinvr** [comment]
Hello, I will change than and come with a new PR.

**Pull request closed without merging**
