### PR TITLE
Update Shelly-as-a-Switch.groovy

### PR DESCRIPTION
**Pull request by rudam**
Hi guys. I made a couple of tweaks for EM and EM3 devices reflecting current functionality of the Shelly firmware (1.8.1). I am practically newbie to Hubitat, so, please, do a review of my changes.

### CODE REVIEW

**Comment by sgrayban** [comment]
I'm looking into this already. I'm not sure if something changed in the groovy libraries but the current code used to work flawlessly. I have done some testing on my side.

Line 178 should work as intended but the || doesn't seem to work the first time around. If I change that to && and reload the device page the settings show up for the EM channel and once I revert the && back to || things seem to be fixed and the settings stay for the device.

Very odd... can you test that on your side using the default/current driver code?

What you need to test is this line 178
`    if (getDataValue("model") == "SHEM" || getDataValue("model") == "SHEM-3") {`

change to
`    if (getDataValue("model") == "SHEM" && getDataValue("model") == "SHEM-3") {`

then reload the device and see if the settings show up?

**Comment by rudam** [comment]
You are right, Scott, it looks like an error. My patch changing this part of code completely. What I changed regarding an original line 173 is the split of inputs for SHEM / SHEM-3. The reason is the different number of channels (2, resp. 3) provided by these two devices and removal of ctraf_type input for SHEM-3 which is useless due to removal of it from the Shelly API since FW ver 1.7.0 as remarked.

New code looks like this, so to separated cases instead of one combined:

```
    if (getDataValue("model") == "SHEM") {
        input("eMeter", "number", title:"eMeter Channel", description:"0 or 1 :", defaultValue:"0" , required: true)
        input("ctraf", "number", title:"Current Amperage(ctraf_type)", description:"50 or 120:", defaultValue:"50" , required: true)
    }

    if (getDataValue("model") == "SHEM-3") {
        input("eMeter", "number", title:"eMeter Channel", description:"0, 1 or 2 :", defaultValue:"0" , required: true)
    }
```

**Comment by sgrayban** [comment]
Ok I didn't know about the ctraf_type being removed. It's not like Shelly developers ever post changelogs so us smarthome developers can keep up with the changes.

I also found another bug that I will sort out today. What is your username on the hubitat forum?

**Comment by ShellyUSA** [comment]
For future reference, Change log for Shelly firmware updates is available at this URL, going back to 1.7 in May 2020:

https://shelly.cloud/category/changelog/

**Comment by sgrayban** [comment]
Hmmm ctraf does seem to be in the docs though...
ctraf_type	number	Current transformer type, 50 or 120 - currently unused

image

Are the Shelly Docs wrong??

**Comment by sgrayban** [comment]
@rudam I have some code for you to test. PM me on the hubitat forum please.

**Comment by rudam** [comment]
> Hmmm ctraf does seem to be in the docs though...
> ctraf_type number Current transformer type, 50 or 120 - **currently unused**

Hi. Shelly is reporting ctraf_type, but it looks like it can not be changed. That is what the "currently unused" remark probably means.

Will PM you.
Thx

**Comment by sgrayban** [comment]
Unused doesn't mean it can't be set. I can set it via my code...

```
"emeters": [
{
"name": null,
"appliance_type": "General",
"ctraf_type": 50,
"max_power": 0
},
{
"name": null,
"appliance_type": "General",
"ctraf_type": 50,
"max_power": 0
}
]
```

**Pull request closed without merging**
