### PR TITLE
Add a few preferences to Motion 2.

### PR DESCRIPTION
**Pull request by DanielWinks**

### CODE REVIEW

**Comment by sgrayban** [comment]
Are you following the versioning I set in drivers I already coded because that version notifies users of a new version that has been uploaded. It seems you are just willy nilly editing and not doing things the way I started.

**Comment by DanielWinks** [comment]
No, I am not. Like I said previously, versioning is handled through Hubitat Package Manager manifests. I'll be removing whatever versioning you had set up once all the previous drivers are migrated to HPM as well. Having users check some file on GitHub is not a good user experience when HPM is available.

**Comment by sgrayban** [comment]
Users don't check... the driver does it automatically and second the license file you have does not attribute `Copyright © 2020 Allterco Robotics US` at all, it is a generic boiler plate for Apache License Version 2.0

If you are going to take over the coding the years and hours I put into this at least do it with a little respect to me.

**Comment by DanielWinks** [comment]
Like I've said a few times now, none of the drivers I'm writing will be using your versioning thing. They're in Hubitat Package Manager. Versioning is handled there. The License is handled there. There's no need for whatever update check thing you had in the older drivers since HPM handles that, AND HPM can install and update the drivers for the users as well, including automatically updating them for them, if they so choose that option. Being notified of a new version does little good if the users still need to come get the newer version off GitHub.

HPM is what everyone using Hubitat expects for finding, installing, and updating drivers and apps. What I'm adding will be using it.

**Pull request merged**
